module.exports={
    addCompany:{
        title:"shema za dodavanje kompanije",
        type:"object",
        properties:{
            name:{
                type:"string",
                isNotEmpty:true,
                maxLength:50,
            },
            description:{
                type:"string",
                isNotEmpty:true,
                
            },
            ICAO:{
                type:"string",
                isNotEmpty:true,
                maxLength:4,
                minLength:1
            },
            IATA:{
                type:"string",
                isNotEmpty:true,
                maxLength:4,
                minLength:1
            },
            country:{
                type:"string",
                isNotEmpty:true,
                maxLength:30,
                minLength:1
            },
            baseHub:{
                type:"string",
                isNotEmpty:true,
                maxLength:20,
                minLength:1  
            },
            founded:{
                type:"string",
                isNotEmpty:true,
            },
            imgPath:{
                type:"string",
                isNotEmpty:true,
            },
            logoPath:{
                type:"string",
                isNotEmpty:true,
            },
            numOfAircraft:{
                type:"number",
            },
            list_id:{
                type:"number",
            },
        }
    }
}